# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2006-2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_stack
crypto_stack_TEMPLATE = SUBLIBCRYPTO
crypto_stack_DEFS = OPENSSL_NO_DEPRECATED
crypto_stack_SOURCES = \
	stack.c
$(evalcall VBOX_OPENSSL_X86,crypto_stack)

include $(FILE_KBUILD_SUB_FOOTER)
