# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_seed
crypto_seed_TEMPLATE = SUBLIBCRYPTO
crypto_seed_DEFS = OPENSSL_NO_DEPRECATED
crypto_seed_SOURCES = \
	seed.c \
	seed_cbc.c \
	seed_cfb.c \
	seed_ecb.c \
	seed_ofb.c
$(evalcall VBOX_OPENSSL_X86,crypto_seed)

include $(FILE_KBUILD_SUB_FOOTER)
