/* $Id$ */
/** @file
 * VBoxNetFltNotify.idl - Network Filter Driver (Host), Windows Specific Code. Integration with IntNet/NetFlt
 */

/*
 * Copyright (C) 2008 Oracle Corporation
 *
 * This file is part of VirtualBox Open Source Edition (OSE), as
 * available from http://www.virtualbox.org. This file is free software;
 * you can redistribute it and/or modify it under the terms of the GNU
 * General Public License (GPL) as published by the Free Software
 * Foundation, in version 2 as it comes in the "COPYING" file of the
 * VirtualBox OSE distribution. VirtualBox OSE is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
 */
/*
 * Based in part on Microsoft DDK sample code for Sample Notify Object
 *+---------------------------------------------------------------------------
 *
 *  Microsoft Windows
 *  Copyright (C) Microsoft Corporation, 1992-2001.
 *
 *----------------------------------------------------------------------------
 */
#include <netcfgn.idl>

[
    uuid(1ea703af-a150-4fdd-83dc-c07a7a460c7e),
    version(1.0),
    helpstring("VirtualBox Bridged Networking Driver Notify Object 1.0 Type Library")
]
library VBoxNetFltNotifyLib
{
    [
        uuid(c631480a-acbe-4add-bb1d-3ed8aa52b5d9),
        helpstring("VirtualBox Bridged Networking Driver Notify Object Class")
    ]
    coclass VBoxNetFltNotify
    {
       [restricted] interface INetCfgComponentControl;
       [restricted] interface INetCfgComponentNotifyBinding;
    };
};