Import('*')

env = env.Clone()

env.PkgUseModules('DRM')

env.Append(CPPDEFINES = [
    'HAVE_STDINT_H',
    '-D_FILE_OFFSET_BITS=64',
])

env.Prepend(CPPPATH = [
    '#/src/gallium/drivers/svga',
    '#/src/gallium/drivers/svga/include',
])

sources = env.ParseSourceList('Makefile.sources', 'C_SOURCES')

svgadrm = env.ConvenienceLibrary(
    target = 'svgadrm',
    source = sources,
)

Export('svgadrm')
