# $Id: Makefile.kmk 118412 2017-10-17 14:26:02Z bird $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2006-2017 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_lhash
crypto_lhash_TEMPLATE = SUBLIBCRYPTO
crypto_lhash_DEFS = OPENSSL_NO_DEPRECATED
crypto_lhash_SOURCES = \
	lhash.c \
	lh_stats.c
$(evalcall VBOX_OPENSSL_X86,crypto_lhash)

include $(FILE_KBUILD_SUB_FOOTER)
