# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_aria
crypto_aria_TEMPLATE = SUBLIBCRYPTO
crypto_aria_DEFS = OPENSSL_NO_DEPRECATED
crypto_aria_SOURCES = \
	aria.c
$(evalcall VBOX_OPENSSL_X86,crypto_aria)

include $(FILE_KBUILD_SUB_FOOTER)
