# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_lhash
crypto_lhash_TEMPLATE = SUBLIBCRYPTO
crypto_lhash_DEFS = OPENSSL_NO_DEPRECATED
crypto_lhash_SOURCES = \
	lh_stats.c \
	lhash.c
$(evalcall VBOX_OPENSSL_X86,crypto_lhash)

include $(FILE_KBUILD_SUB_FOOTER)
