# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_hmac
crypto_hmac_TEMPLATE = SUBLIBCRYPTO
crypto_hmac_DEFS = OPENSSL_NO_DEPRECATED
crypto_hmac_SOURCES = \
	hm_ameth.c \
	hm_pmeth.c \
	hmac.c
$(evalcall VBOX_OPENSSL_X86,crypto_hmac)

include $(FILE_KBUILD_SUB_FOOTER)
