/** @file
 * IPRT - Symbol Mangling.
 *
 * This header is used to mangle public IPRT symbol to make it possible to have
 * several IPRT version loaded into one symbol space at the same time.  To
 * enable symbol mangling you create a header which the compiler includes for
 * every compilation unit (check out the -include option of gcc).  Your header
 * will define RT_MANGLER(name) and then include this header to set up the
 * actual mappings.
 */

/*
 * Copyright (C) 2011 Oracle Corporation
 *
 * This file is part of VirtualBox Open Source Edition (OSE), as
 * available from http://www.virtualbox.org. This file is free software;
 * you can redistribute it and/or modify it under the terms of the GNU
 * General Public License (GPL) as published by the Free Software
 * Foundation, in version 2 as it comes in the "COPYING" file of the
 * VirtualBox OSE distribution. VirtualBox OSE is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
 *
 * The contents of this file may alternatively be used under the terms
 * of the Common Development and Distribution License Version 1.0
 * (CDDL) only, as it comes in the "COPYING.CDDL" file of the
 * VirtualBox OSE distribution, in which case the provisions of the
 * CDDL are applicable instead of those of the GPL.
 *
 * You may elect to license modified versions of this file under the
 * terms and conditions of either the GPL or the CDDL or both.
 */

#ifndef ___iprt_mangling_h
#define ___iprt_mangling_h

#ifndef RT_MANGLER
# error "RT_MANGLER is not defined."
#endif

/** @def RT_WITH_MANGLING
 * Indicates that we're mangling symbols.  */
#define RT_WITH_MANGLING


/*
 * Stable functions (alphabetical order):
 */
#define RTAssertAreQuiet                RT_MANGLER(RTAssertAreQuiet)
#define RTAssertMayPanic                RT_MANGLER(RTAssertMayPanic)
#define RTAssertMsg1                    RT_MANGLER(RTAssertMsg1)
#define RTAssertMsg1Weak                RT_MANGLER(RTAssertMsg1Weak)
#define RTAssertMsg2Add                 RT_MANGLER(RTAssertMsg2Add)
#define RTAssertMsg2AddV                RT_MANGLER(RTAssertMsg2AddV)
#define RTAssertMsg2AddWeak             RT_MANGLER(RTAssertMsg2AddWeak)
#define RTAssertMsg2AddWeakV            RT_MANGLER(RTAssertMsg2AddWeakV)
#define RTAssertMsg2                    RT_MANGLER(RTAssertMsg2)
#define RTAssertMsg2V                   RT_MANGLER(RTAssertMsg2V)
#define RTAssertMsg2Weak                RT_MANGLER(RTAssertMsg2Weak)
#define RTAssertMsg2WeakV               RT_MANGLER(RTAssertMsg2WeakV)
#define RTAssertSetMayPanic             RT_MANGLER(RTAssertSetMayPanic)
#define RTAssertSetQuiet                RT_MANGLER(RTAssertSetQuiet)
#define RTAssertShouldPanic             RT_MANGLER(RTAssertShouldPanic)
#define RTCrc32Finish                   RT_MANGLER(RTCrc32Finish)
#define RTCrc32                         RT_MANGLER(RTCrc32)
#define RTCrc32Process                  RT_MANGLER(RTCrc32Process)
#define RTCrc32Start                    RT_MANGLER(RTCrc32Start)
#define RTErrConvertFromErrno           RT_MANGLER(RTErrConvertFromErrno)
#define RTErrConvertToErrno             RT_MANGLER(RTErrConvertToErrno)
#define RTHandleTableAllocWithCtx       RT_MANGLER(RTHandleTableAllocWithCtx)
#define RTHandleTableCreateEx           RT_MANGLER(RTHandleTableCreateEx)
#define RTHandleTableCreate             RT_MANGLER(RTHandleTableCreate)
#define RTHandleTableDestroy            RT_MANGLER(RTHandleTableDestroy)
#define RTHandleTableFreeWithCtx        RT_MANGLER(RTHandleTableFreeWithCtx)
#define RTHandleTableLookupWithCtx      RT_MANGLER(RTHandleTableLookupWithCtx)
#define RTHeapSimpleAlloc               RT_MANGLER(RTHeapSimpleAlloc)
#define RTHeapSimpleAllocZ              RT_MANGLER(RTHeapSimpleAllocZ)
#define RTHeapSimpleDump                RT_MANGLER(RTHeapSimpleDump)
#define RTHeapSimpleFree                RT_MANGLER(RTHeapSimpleFree)
#define RTHeapSimpleGetFreeSize         RT_MANGLER(RTHeapSimpleGetFreeSize)
#define RTHeapSimpleGetHeapSize         RT_MANGLER(RTHeapSimpleGetHeapSize)
#define RTHeapSimpleInit                RT_MANGLER(RTHeapSimpleInit)
#define RTHeapSimpleRelocate            RT_MANGLER(RTHeapSimpleRelocate)
#define RTHeapSimpleSize                RT_MANGLER(RTHeapSimpleSize)
#define RTLogBackdoorPrintf             RT_MANGLER(RTLogBackdoorPrintf)
#define RTLogBackdoorPrintfV            RT_MANGLER(RTLogBackdoorPrintfV)
#define RTLogCloneRC                    RT_MANGLER(RTLogCloneRC)
#define RTLogComPrintf                  RT_MANGLER(RTLogComPrintf)
#define RTLogComPrintfV                 RT_MANGLER(RTLogComPrintfV)
#define RTLogCopyGroupsAndFlags         RT_MANGLER(RTLogCopyGroupsAndFlags)
#define RTLogCreateEx                   RT_MANGLER(RTLogCreateEx)
#define RTLogCreateExV                  RT_MANGLER(RTLogCreateExV)
#define RTLogCreate                     RT_MANGLER(RTLogCreate)
#define RTLogDefaultInit                RT_MANGLER(RTLogDefaultInit)
#define RTLogDefaultInstance            RT_MANGLER(RTLogDefaultInstance)
#define RTLogDestinations               RT_MANGLER(RTLogDestinations)
#define RTLogDestroy                    RT_MANGLER(RTLogDestroy)
#define RTLogFlags                      RT_MANGLER(RTLogFlags)
#define RTLogFlush                      RT_MANGLER(RTLogFlush)
#define RTLogFlushRC                    RT_MANGLER(RTLogFlushRC)
#define RTLogFlushToLogger              RT_MANGLER(RTLogFlushToLogger)
#define RTLogFormatV                    RT_MANGLER(RTLogFormatV)
#define RTLogGetDefaultInstance         RT_MANGLER(RTLogGetDefaultInstance)
#define RTLogGetDestinations            RT_MANGLER(RTLogGetDestinations)
#define RTLogGetFlags                   RT_MANGLER(RTLogGetFlags)
#define RTLogGetGroupSettings           RT_MANGLER(RTLogGetGroupSettings)
#define RTLogGroupSettings              RT_MANGLER(RTLogGroupSettings)
#define RTLogLoggerEx                   RT_MANGLER(RTLogLoggerEx)
#define RTLogLoggerExV                  RT_MANGLER(RTLogLoggerExV)
#define RTLogLogger                     RT_MANGLER(RTLogLogger)
#define RTLogLoggerV                    RT_MANGLER(RTLogLoggerV)
#define RTLogPrintf                     RT_MANGLER(RTLogPrintf)
#define RTLogPrintfV                    RT_MANGLER(RTLogPrintfV)
#define RTLogRelDefaultInstance         RT_MANGLER(RTLogRelDefaultInstance)
#define RTLogRelLogger                  RT_MANGLER(RTLogRelLogger)
#define RTLogRelLoggerV                 RT_MANGLER(RTLogRelLoggerV)
#define RTLogRelPrintf                  RT_MANGLER(RTLogRelPrintf)
#define RTLogRelPrintfV                 RT_MANGLER(RTLogRelPrintfV)
#define RTLogRelSetBuffering            RT_MANGLER(RTLogRelSetBuffering)
#define RTLogRelSetDefaultInstance      RT_MANGLER(RTLogRelSetDefaultInstance)
#define RTLogSetBuffering               RT_MANGLER(RTLogSetBuffering)
#define RTLogSetCustomPrefixCallback    RT_MANGLER(RTLogSetCustomPrefixCallback)
#define RTLogSetDefaultInstance         RT_MANGLER(RTLogSetDefaultInstance)
#define RTLogSetDefaultInstanceThread   RT_MANGLER(RTLogSetDefaultInstanceThread)
#define RTLogWriteCom                   RT_MANGLER(RTLogWriteCom)
#define RTLogWriteDebugger              RT_MANGLER(RTLogWriteDebugger)
#define RTLogWriteStdErr                RT_MANGLER(RTLogWriteStdErr)
#define RTLogWriteStdOut                RT_MANGLER(RTLogWriteStdOut)
#define RTLogWriteUser                  RT_MANGLER(RTLogWriteUser)
#define RTMemAllocExTag                 RT_MANGLER(RTMemAllocExTag)
#define RTMemAllocTag                   RT_MANGLER(RTMemAllocTag)
#define RTMemAllocVarTag                RT_MANGLER(RTMemAllocVarTag)
#define RTMemAllocZTag                  RT_MANGLER(RTMemAllocZTag)
#define RTMemAllocZVarTag               RT_MANGLER(RTMemAllocZVarTag)
#define RTMemContAlloc                  RT_MANGLER(RTMemContAlloc)
#define RTMemContFree                   RT_MANGLER(RTMemContFree)
#define RTMemDupExTag                   RT_MANGLER(RTMemDupExTag)
#define RTMemDupTag                     RT_MANGLER(RTMemDupTag)
#define RTMemExecAllocTag               RT_MANGLER(RTMemExecAllocTag)
#define RTMemExecFree                   RT_MANGLER(RTMemExecFree)
#define RTMemFreeEx                     RT_MANGLER(RTMemFreeEx)
#define RTMemFree                       RT_MANGLER(RTMemFree)
#define RTMemReallocTag                 RT_MANGLER(RTMemReallocTag)
#define RTMemTmpAllocTag                RT_MANGLER(RTMemTmpAllocTag)
#define RTMemTmpAllocZTag               RT_MANGLER(RTMemTmpAllocZTag)
#define RTMemTmpFree                    RT_MANGLER(RTMemTmpFree)
#define RTMpCpuIdFromSetIndex           RT_MANGLER(RTMpCpuIdFromSetIndex)
#define RTMpCpuId                       RT_MANGLER(RTMpCpuId)
#define RTMpCpuIdToSetIndex             RT_MANGLER(RTMpCpuIdToSetIndex)
#define RTMpGetArraySize                RT_MANGLER(RTMpGetArraySize)
#define RTMpGetCount                    RT_MANGLER(RTMpGetCount)
#define RTMpGetMaxCpuId                 RT_MANGLER(RTMpGetMaxCpuId)
#define RTMpGetOnlineCount              RT_MANGLER(RTMpGetOnlineCount)
#define RTMpGetOnlineSet                RT_MANGLER(RTMpGetOnlineSet)
#define RTMpGetSet                      RT_MANGLER(RTMpGetSet)
#define RTMpIsCpuOnline                 RT_MANGLER(RTMpIsCpuOnline)
#define RTMpIsCpuPossible               RT_MANGLER(RTMpIsCpuPossible)
#define RTMpIsCpuWorkPending            RT_MANGLER(RTMpIsCpuWorkPending)
#define RTMpNotificationDeregister      RT_MANGLER(RTMpNotificationDeregister)
#define RTMpNotificationRegister        RT_MANGLER(RTMpNotificationRegister)
#define RTMpOnAll                       RT_MANGLER(RTMpOnAll)
#define RTMpOnOthers                    RT_MANGLER(RTMpOnOthers)
#define RTMpOnSpecific                  RT_MANGLER(RTMpOnSpecific)
#define RTMpPokeCpu                     RT_MANGLER(RTMpPokeCpu)
#define RTNetIPv4AddDataChecksum        RT_MANGLER(RTNetIPv4AddDataChecksum)
#define RTNetIPv4AddTCPChecksum         RT_MANGLER(RTNetIPv4AddTCPChecksum)
#define RTNetIPv4AddUDPChecksum         RT_MANGLER(RTNetIPv4AddUDPChecksum)
#define RTNetIPv4FinalizeChecksum       RT_MANGLER(RTNetIPv4FinalizeChecksum)
#define RTNetIPv4HdrChecksum            RT_MANGLER(RTNetIPv4HdrChecksum)
#define RTNetIPv4IsDHCPValid            RT_MANGLER(RTNetIPv4IsDHCPValid)
#define RTNetIPv4IsHdrValid             RT_MANGLER(RTNetIPv4IsHdrValid)
#define RTNetIPv4IsTCPSizeValid         RT_MANGLER(RTNetIPv4IsTCPSizeValid)
#define RTNetIPv4IsTCPValid             RT_MANGLER(RTNetIPv4IsTCPValid)
#define RTNetIPv4IsUDPSizeValid         RT_MANGLER(RTNetIPv4IsUDPSizeValid)
#define RTNetIPv4IsUDPValid             RT_MANGLER(RTNetIPv4IsUDPValid)
#define RTNetIPv4PseudoChecksumBits     RT_MANGLER(RTNetIPv4PseudoChecksumBits)
#define RTNetIPv4PseudoChecksum         RT_MANGLER(RTNetIPv4PseudoChecksum)
#define RTNetIPv4TCPChecksum            RT_MANGLER(RTNetIPv4TCPChecksum)
#define RTNetIPv4UDPChecksum            RT_MANGLER(RTNetIPv4UDPChecksum)
#define RTNetIPv6PseudoChecksumBits     RT_MANGLER(RTNetIPv6PseudoChecksumBits)
#define RTNetIPv6PseudoChecksumEx       RT_MANGLER(RTNetIPv6PseudoChecksumEx)
#define RTNetIPv6PseudoChecksum         RT_MANGLER(RTNetIPv6PseudoChecksum)
#define RTNetTCPChecksum                RT_MANGLER(RTNetTCPChecksum)
#define RTNetUDPChecksum                RT_MANGLER(RTNetUDPChecksum)
#define RTPowerNotificationDeregister   RT_MANGLER(RTPowerNotificationDeregister)
#define RTPowerNotificationRegister     RT_MANGLER(RTPowerNotificationRegister)
#define RTPowerSignalEvent              RT_MANGLER(RTPowerSignalEvent)
#define RTProcSelf                      RT_MANGLER(RTProcSelf)
#define RTR0AssertPanicSystem           RT_MANGLER(RTR0AssertPanicSystem)
#define RTR0Init                        RT_MANGLER(RTR0Init)
#define RTR0MemAreKrnlAndUsrDifferent   RT_MANGLER(RTR0MemAreKrnlAndUsrDifferent)
#define RTR0MemExecDonate               RT_MANGLER(RTR0MemExecDonate)
#define RTR0MemExecInit                 RT_MANGLER(RTR0MemExecInit)
#define RTR0MemKernelIsValidAddr        RT_MANGLER(RTR0MemKernelIsValidAddr)
#define RTR0MemObjAddress               RT_MANGLER(RTR0MemObjAddress)
#define RTR0MemObjAddressR3             RT_MANGLER(RTR0MemObjAddressR3)
#define RTR0MemObjAllocContTag          RT_MANGLER(RTR0MemObjAllocContTag)
#define RTR0MemObjAllocLowTag           RT_MANGLER(RTR0MemObjAllocLowTag)
#define RTR0MemObjAllocPageTag          RT_MANGLER(RTR0MemObjAllocPageTag)
#define RTR0MemObjAllocPhysExTag        RT_MANGLER(RTR0MemObjAllocPhysExTag)
#define RTR0MemObjAllocPhysNCTag        RT_MANGLER(RTR0MemObjAllocPhysNCTag)
#define RTR0MemObjAllocPhysTag          RT_MANGLER(RTR0MemObjAllocPhysTag)
#define RTR0MemObjEnterPhysTag          RT_MANGLER(RTR0MemObjEnterPhysTag)
#define RTR0MemObjFree                  RT_MANGLER(RTR0MemObjFree)
#define RTR0MemObjGetPagePhysAddr       RT_MANGLER(RTR0MemObjGetPagePhysAddr)
#define RTR0MemObjIsMapping             RT_MANGLER(RTR0MemObjIsMapping)
#define RTR0MemObjLockKernelTag         RT_MANGLER(RTR0MemObjLockKernelTag)
#define RTR0MemObjLockUserTag           RT_MANGLER(RTR0MemObjLockUserTag)
#define RTR0MemObjMapKernelExTag        RT_MANGLER(RTR0MemObjMapKernelExTag)
#define RTR0MemObjMapKernelTag          RT_MANGLER(RTR0MemObjMapKernelTag)
#define RTR0MemObjMapUserTag            RT_MANGLER(RTR0MemObjMapUserTag)
#define RTR0MemObjProtect               RT_MANGLER(RTR0MemObjProtect)
#define RTR0MemObjReserveKernelTag      RT_MANGLER(RTR0MemObjReserveKernelTag)
#define RTR0MemObjReserveUserTag        RT_MANGLER(RTR0MemObjReserveUserTag)
#define RTR0MemObjSize                  RT_MANGLER(RTR0MemObjSize)
#define RTR0MemUserCopyFrom             RT_MANGLER(RTR0MemUserCopyFrom)
#define RTR0MemUserCopyTo               RT_MANGLER(RTR0MemUserCopyTo)
#define RTR0MemUserIsValidAddr          RT_MANGLER(RTR0MemUserIsValidAddr)
#define RTR0ProcHandleSelf              RT_MANGLER(RTR0ProcHandleSelf)
#define RTR0TermForced                  RT_MANGLER(RTR0TermForced)
#define RTR0Term                        RT_MANGLER(RTR0Term)
#define RTSemEventCreateEx              RT_MANGLER(RTSemEventCreateEx)
#define RTSemEventCreate                RT_MANGLER(RTSemEventCreate)
#define RTSemEventDestroy               RT_MANGLER(RTSemEventDestroy)
#define RTSemEventGetResolution         RT_MANGLER(RTSemEventGetResolution)
#define RTSemEventMultiCreateEx         RT_MANGLER(RTSemEventMultiCreateEx)
#define RTSemEventMultiCreate           RT_MANGLER(RTSemEventMultiCreate)
#define RTSemEventMultiDestroy          RT_MANGLER(RTSemEventMultiDestroy)
#define RTSemEventMultiGetResolution    RT_MANGLER(RTSemEventMultiGetResolution)
#define RTSemEventMultiReset            RT_MANGLER(RTSemEventMultiReset)
#define RTSemEventMultiSignal           RT_MANGLER(RTSemEventMultiSignal)
#define RTSemEventMultiWaitExDebug      RT_MANGLER(RTSemEventMultiWaitExDebug)
#define RTSemEventMultiWaitEx           RT_MANGLER(RTSemEventMultiWaitEx)
#define RTSemEventMultiWait             RT_MANGLER(RTSemEventMultiWait)
#define RTSemEventMultiWaitNoResume     RT_MANGLER(RTSemEventMultiWaitNoResume)
#define RTSemEventSignal                RT_MANGLER(RTSemEventSignal)
#define RTSemEventWaitExDebug           RT_MANGLER(RTSemEventWaitExDebug)
#define RTSemEventWaitEx                RT_MANGLER(RTSemEventWaitEx)
#define RTSemEventWait                  RT_MANGLER(RTSemEventWait)
#define RTSemEventWaitNoResume          RT_MANGLER(RTSemEventWaitNoResume)
#define RTSemFastMutexCreate            RT_MANGLER(RTSemFastMutexCreate)
#define RTSemFastMutexDestroy           RT_MANGLER(RTSemFastMutexDestroy)
#define RTSemFastMutexRelease           RT_MANGLER(RTSemFastMutexRelease)
#define RTSemFastMutexRequest           RT_MANGLER(RTSemFastMutexRequest)
#define RTSemMutexCreate                RT_MANGLER(RTSemMutexCreate)
#define RTSemMutexDestroy               RT_MANGLER(RTSemMutexDestroy)
#define RTSemMutexIsOwned               RT_MANGLER(RTSemMutexIsOwned)
#define RTSemMutexRelease               RT_MANGLER(RTSemMutexRelease)
#define RTSemMutexRequestDebug          RT_MANGLER(RTSemMutexRequestDebug)
#define RTSemMutexRequest               RT_MANGLER(RTSemMutexRequest)
#define RTSemMutexRequestNoResumeDebug  RT_MANGLER(RTSemMutexRequestNoResumeDebug)
#define RTSemMutexRequestNoResume       RT_MANGLER(RTSemMutexRequestNoResume)
#define RTSemSpinMutexCreate            RT_MANGLER(RTSemSpinMutexCreate)
#define RTSemSpinMutexDestroy           RT_MANGLER(RTSemSpinMutexDestroy)
#define RTSemSpinMutexRelease           RT_MANGLER(RTSemSpinMutexRelease)
#define RTSemSpinMutexRequest           RT_MANGLER(RTSemSpinMutexRequest)
#define RTSemSpinMutexTryRequest        RT_MANGLER(RTSemSpinMutexTryRequest)
#define RTSpinlockAcquire               RT_MANGLER(RTSpinlockAcquire)
#define RTSpinlockAcquireNoInts         RT_MANGLER(RTSpinlockAcquireNoInts)
#define RTSpinlockCreate                RT_MANGLER(RTSpinlockCreate)
#define RTSpinlockDestroy               RT_MANGLER(RTSpinlockDestroy)
#define RTSpinlockRelease               RT_MANGLER(RTSpinlockRelease)
#define RTSpinlockReleaseNoInts         RT_MANGLER(RTSpinlockReleaseNoInts)
#define RTStrCopy                       RT_MANGLER(RTStrCopy)
#define RTStrEnd                        RT_MANGLER(RTStrEnd)
#define RTStrFormat                     RT_MANGLER(RTStrFormat)
#define RTStrFormatNumber               RT_MANGLER(RTStrFormatNumber)
#define RTStrFormatTypeDeregister       RT_MANGLER(RTStrFormatTypeDeregister)
#define RTStrFormatTypeRegister         RT_MANGLER(RTStrFormatTypeRegister)
#define RTStrFormatTypeSetUser          RT_MANGLER(RTStrFormatTypeSetUser)
#define RTStrFormatV                    RT_MANGLER(RTStrFormatV)
#define RTStrPrintfEx                   RT_MANGLER(RTStrPrintfEx)
#define RTStrPrintfExV                  RT_MANGLER(RTStrPrintfExV)
#define RTStrPrintf                     RT_MANGLER(RTStrPrintf)
#define RTStrPrintfV                    RT_MANGLER(RTStrPrintfV)
#define RTStrToInt16Ex                  RT_MANGLER(RTStrToInt16Ex)
#define RTStrToInt16Full                RT_MANGLER(RTStrToInt16Full)
#define RTStrToInt16                    RT_MANGLER(RTStrToInt16)
#define RTStrToInt32Ex                  RT_MANGLER(RTStrToInt32Ex)
#define RTStrToInt32Full                RT_MANGLER(RTStrToInt32Full)
#define RTStrToInt32                    RT_MANGLER(RTStrToInt32)
#define RTStrToInt64Ex                  RT_MANGLER(RTStrToInt64Ex)
#define RTStrToInt64Full                RT_MANGLER(RTStrToInt64Full)
#define RTStrToInt64                    RT_MANGLER(RTStrToInt64)
#define RTStrToInt8Ex                   RT_MANGLER(RTStrToInt8Ex)
#define RTStrToInt8Full                 RT_MANGLER(RTStrToInt8Full)
#define RTStrToInt8                     RT_MANGLER(RTStrToInt8)
#define RTStrToUInt16Ex                 RT_MANGLER(RTStrToUInt16Ex)
#define RTStrToUInt16Full               RT_MANGLER(RTStrToUInt16Full)
#define RTStrToUInt16                   RT_MANGLER(RTStrToUInt16)
#define RTStrToUInt32Ex                 RT_MANGLER(RTStrToUInt32Ex)
#define RTStrToUInt32Full               RT_MANGLER(RTStrToUInt32Full)
#define RTStrToUInt32                   RT_MANGLER(RTStrToUInt32)
#define RTStrToUInt64Ex                 RT_MANGLER(RTStrToUInt64Ex)
#define RTStrToUInt64Full               RT_MANGLER(RTStrToUInt64Full)
#define RTStrToUInt64                   RT_MANGLER(RTStrToUInt64)
#define RTStrToUInt8Ex                  RT_MANGLER(RTStrToUInt8Ex)
#define RTStrToUInt8Full                RT_MANGLER(RTStrToUInt8Full)
#define RTStrToUInt8                    RT_MANGLER(RTStrToUInt8)
#define RTThreadIsInInterrupt           RT_MANGLER(RTThreadIsInInterrupt)
#define RTThreadNativeSelf              RT_MANGLER(RTThreadNativeSelf)
#define RTThreadPreemptDisable          RT_MANGLER(RTThreadPreemptDisable)
#define RTThreadPreemptIsEnabled        RT_MANGLER(RTThreadPreemptIsEnabled)
#define RTThreadPreemptIsPending        RT_MANGLER(RTThreadPreemptIsPending)
#define RTThreadPreemptIsPendingTrusty  RT_MANGLER(RTThreadPreemptIsPendingTrusty)
#define RTThreadPreemptIsPossible       RT_MANGLER(RTThreadPreemptIsPossible)
#define RTThreadPreemptRestore          RT_MANGLER(RTThreadPreemptRestore)
#define RTThreadSleep                   RT_MANGLER(RTThreadSleep)
#define RTThreadYield                   RT_MANGLER(RTThreadYield)
#define RTTimeExplode                   RT_MANGLER(RTTimeExplode)
#define RTTimeImplode                   RT_MANGLER(RTTimeImplode)
#define RTTimeIsLeapYear                RT_MANGLER(RTTimeIsLeapYear)
#define RTTimeMilliTS                   RT_MANGLER(RTTimeMilliTS)
#define RTTimeNanoTS                    RT_MANGLER(RTTimeNanoTS)
#define RTTimeNormalize                 RT_MANGLER(RTTimeNormalize)
#define RTTimeNow                       RT_MANGLER(RTTimeNow)
#define RTTimerCanDoHighResolution      RT_MANGLER(RTTimerCanDoHighResolution)
#define RTTimerChangeInterval           RT_MANGLER(RTTimerChangeInterval)
#define RTTimerCreateEx                 RT_MANGLER(RTTimerCreateEx)
#define RTTimerCreate                   RT_MANGLER(RTTimerCreate)
#define RTTimerDestroy                  RT_MANGLER(RTTimerDestroy)
#define RTTimerGetSystemGranularity     RT_MANGLER(RTTimerGetSystemGranularity)
#define RTTimerReleaseSystemGranularity RT_MANGLER(RTTimerReleaseSystemGranularity)
#define RTTimerRequestSystemGranularity RT_MANGLER(RTTimerRequestSystemGranularity)
#define RTTimerStart                    RT_MANGLER(RTTimerStart)
#define RTTimerStop                     RT_MANGLER(RTTimerStop)
#define RTTimeSpecToString              RT_MANGLER(RTTimeSpecToString)
#define RTTimeSystemMilliTS             RT_MANGLER(RTTimeSystemMilliTS)
#define RTTimeSystemNanoTS              RT_MANGLER(RTTimeSystemNanoTS)
#define RTTimeToString                  RT_MANGLER(RTTimeToString)
#define RTUuidClear                     RT_MANGLER(RTUuidClear)
#define RTUuidCompare2Strs              RT_MANGLER(RTUuidCompare2Strs)
#define RTUuidCompare                   RT_MANGLER(RTUuidCompare)
#define RTUuidCompareStr                RT_MANGLER(RTUuidCompareStr)
#define RTUuidFromStr                   RT_MANGLER(RTUuidFromStr)
#define RTUuidFromUtf16                 RT_MANGLER(RTUuidFromUtf16)
#define RTUuidIsNull                    RT_MANGLER(RTUuidIsNull)
#define RTUuidToStr                     RT_MANGLER(RTUuidToStr)
#define RTUuidToUtf16                   RT_MANGLER(RTUuidToUtf16)
/** @todo the list is incomplete! */


/*
 * Stable variables (alphabetical order):
 */
#define g_pszRTAssertExpr               RT_MANGLER(g_pszRTAssertExpr)
#define g_pszRTAssertFile               RT_MANGLER(g_pszRTAssertFile)
#define g_pszRTAssertFunction           RT_MANGLER(g_pszRTAssertFunction)
#define g_u32RTAssertLine               RT_MANGLER(g_u32RTAssertLine)
#define g_szRTAssertMsg1                RT_MANGLER(g_szRTAssertMsg1)
#define g_szRTAssertMsg2                RT_MANGLER(g_szRTAssertMsg2)
/** @todo the list is incomplete? */



/*
 * Unstable functions (alphabetical order):
 */
/** @todo the list is incomplete! See the .def files. */


/*
 * Unstable variables (alphabetical order):
 */
/* none */


#endif

