# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_objects
crypto_objects_TEMPLATE = SUBLIBCRYPTO
crypto_objects_DEFS = OPENSSL_NO_DEPRECATED
crypto_objects_SOURCES = \
	o_names.c \
	obj_dat.c \
	obj_err.c \
	obj_lib.c \
	obj_xref.c
$(evalcall VBOX_OPENSSL_X86,crypto_objects)

include $(FILE_KBUILD_SUB_FOOTER)
