# $Id$
## @file
# Makefile for the ffmpeg frame buffer module.
#

#
# Copyright (C) 2006-2007 innotek GmbH
#
# innotek GmbH confidential
# All rights reserved
#

DEPTH = ../../../../..
include $(PATH_KBUILD)/header.kmk

DLLS                         = VBoxFFmpegFB
VBoxFFmpegFB_TEMPLATE        = VBOXMAINCLIENTDLL
VBoxFFmpegFB_SDKS            = VBOX_FFMPEG VBOX_LIBPNG VBOX_ZLIB
VBoxFFmpegFB_SOURCES         = FFmpegFB.cpp
VBoxFFmpegFB_CXXFLAGS.linux += -fPIC

include $(PATH_KBUILD)/footer.kmk

