# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_ui
crypto_ui_TEMPLATE = SUBLIBCRYPTO
crypto_ui_DEFS = OPENSSL_NO_DEPRECATED
crypto_ui_SOURCES = \
	ui_err.c \
	ui_lib.c \
	ui_null.c \
	ui_openssl.c \
	ui_util.c
$(evalcall VBOX_OPENSSL_X86,crypto_ui)

include $(FILE_KBUILD_SUB_FOOTER)
