# $Id: Makefile.kmk 118412 2017-10-17 14:26:02Z bird $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2006-2017 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_chacha
crypto_chacha_TEMPLATE = SUBLIBCRYPTO
crypto_chacha_DEFS = OPENSSL_NO_DEPRECATED
crypto_chacha_SOURCES = \
	chacha_enc.c

$(evalcall VBOX_OPENSSL_X86,crypto_chacha)

include $(FILE_KBUILD_SUB_FOOTER)
