# $Id: Makefile.kmk 21700 2007-06-01 16:01:28Z umoeller $
## @file
# Sub-Makefile for the Shared OpenGL Host Service testcases.
#

#
# Copyright (C) 2006-2007 Sun Microsystems, Inc.
#
# This file is part of VirtualBox Open Source Edition (OSE), as
# available from http://www.virtualbox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualBox OSE distribution. VirtualBox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#
# Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
# Clara, CA 95054 USA or visit http://www.sun.com if you need
# additional information or have any questions.
#

DEPTH ?= ../../../../../../..
SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

ifdef VBOX_WITH_TESTCASES
#
# Structure size testcase.
#
PROGRAMS += tstShOpenGL tstOGLSample tstOGLSphere

ifdef VBOX_WITH_64BIT_ADDITIONS
tstShOpenGL_TEMPLATE = VBOXGUESTR3EXE
else
tstShOpenGL_TEMPLATE = VBOXW32GUESTR3
endif
tstShOpenGL_DEFS     = VBOX_HGCM
tstShOpenGL_SOURCES  = tstShOpenGL.cpp
ifdef VBOX_WITH_64BIT_ADDITIONS
tstShOpenGL_LIBS     = $(PATH_SDK_WINPSDK_LIB)/opengl32.lib
else
tstShOpenGL_LIBS     = $(PATH_SDK_W2K3DDKX86_LIB)/opengl32.lib
endif


ifdef VBOX_WITH_64BIT_ADDITIONS
tstOGLSample_TEMPLATE = VBOXGUESTR3EXE
else
tstOGLSample_TEMPLATE = VBOXW32GUESTR3
endif
tstOGLSample_DEFS     =
tstOGLSample_SOURCES  = tstOGLSample.cpp
ifdef VBOX_WITH_64BIT_ADDITIONS
tstOGLSample_LIBS     = $(PATH_SDK_WINPSDK_LIB)/opengl32.lib
else
tstOGLSample_LIBS     = $(PATH_SDK_W2K3DDKX86_LIB)/opengl32.lib
endif


ifdef VBOX_WITH_64BIT_ADDITIONS
tstOGLSphere_TEMPLATE = VBOXGUESTR3EXE
else
tstOGLSphere_TEMPLATE = VBOXW32GUESTR3
endif
tstOGLSphere_DEFS     =
tstOGLSphere_SOURCES  = tstOGLSphere.c
ifdef VBOX_WITH_64BIT_ADDITIONS
tstOGLSphere_LIBS     = $(PATH_SDK_WINPSDK_LIB)/opengl32.lib
else
tstOGLSphere_LIBS     = $(PATH_SDK_W2K3DDKX86_LIB)/opengl32.lib
endif

endif # VBOX_WITH_TESTCASES

include $(KBUILD_PATH)/subfooter.kmk

