// DriConf options specific to radeonsi
DRI_CONF_SECTION_PERFORMANCE
    DRI_CONF_RADEONSI_ENABLE_SISCHED("false")
    DRI_CONF_RADEONSI_ASSUME_NO_Z_FIGHTS("false")
    DRI_CONF_RADEONSI_COMMUTATIVE_BLEND_ADD("false")
DRI_CONF_SECTION_END

DRI_CONF_SECTION_DEBUG
   DRI_CONF_RADEONSI_CLEAR_DB_CACHE_BEFORE_CLEAR("false")
DRI_CONF_SECTION_END
