#!/bin/sh

#
# Copyright (C) 2008-2010 Oracle Corporation
#
# This file is part of VirtualBox Open Source Edition (OSE), as
# available from http://www.virtualbox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualBox OSE distribution. VirtualBox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

GREP=/usr/bin/grep
PS=/bin/ps

RESULT=0

# Check if there are running vms
PROCS=`${PS} -e | ${GREP} -E  "VirtualBoxVM.*startvm|VBoxNetDHCP" | ${GREP} -v grep`
if [ "${PROCS}x" != "x" ]; then
  RESULT=1;
fi

exit $RESULT
