# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_bf
crypto_bf_TEMPLATE = SUBLIBCRYPTO
crypto_bf_DEFS = OPENSSL_NO_DEPRECATED
crypto_bf_SOURCES = \
	bf_cfb64.c \
	bf_ecb.c \
	bf_enc.c \
	bf_ofb64.c \
	bf_skey.c
$(evalcall VBOX_OPENSSL_X86,crypto_bf)

include $(FILE_KBUILD_SUB_FOOTER)
