# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_srp
crypto_srp_TEMPLATE = SUBLIBCRYPTO
crypto_srp_DEFS = OPENSSL_NO_DEPRECATED
crypto_srp_SOURCES = \
	srp_lib.c \
	srp_vfy.c
$(evalcall VBOX_OPENSSL_X86,crypto_srp)

include $(FILE_KBUILD_SUB_FOOTER)
