# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_sm3
crypto_sm3_TEMPLATE = SUBLIBCRYPTO
crypto_sm3_DEFS = OPENSSL_NO_DEPRECATED
crypto_sm3_SOURCES = \
	m_sm3.c \
	sm3.c
$(evalcall VBOX_OPENSSL_X86,crypto_sm3)

include $(FILE_KBUILD_SUB_FOOTER)
