# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_blake2
crypto_blake2_TEMPLATE = SUBLIBCRYPTO
crypto_blake2_DEFS = OPENSSL_NO_DEPRECATED
crypto_blake2_SOURCES = \
	blake2b.c \
	blake2s.c \
	m_blake2b.c \
	m_blake2s.c
$(evalcall VBOX_OPENSSL_X86,crypto_blake2)

include $(FILE_KBUILD_SUB_FOOTER)
