# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_txt_db
crypto_txt_db_TEMPLATE = SUBLIBCRYPTO
crypto_txt_db_DEFS = OPENSSL_NO_DEPRECATED
crypto_txt_db_SOURCES = \
	txt_db.c
$(evalcall VBOX_OPENSSL_X86,crypto_txt_db)

include $(FILE_KBUILD_SUB_FOOTER)
