# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_siphash
crypto_siphash_TEMPLATE = SUBLIBCRYPTO
crypto_siphash_DEFS = OPENSSL_NO_DEPRECATED
crypto_siphash_SOURCES = \
	siphash.c \
	siphash_ameth.c \
	siphash_pmeth.c
$(evalcall VBOX_OPENSSL_X86,crypto_siphash)

include $(FILE_KBUILD_SUB_FOOTER)
