# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_kdf
crypto_kdf_TEMPLATE = SUBLIBCRYPTO
crypto_kdf_DEFS = OPENSSL_NO_DEPRECATED
crypto_kdf_SOURCES = \
	kdf_err.c
$(evalcall VBOX_OPENSSL_X86,crypto_kdf)

include $(FILE_KBUILD_SUB_FOOTER)
