C_SOURCES := \
	r600_buffer_common.c \
	r600_cs.h \
	r600_gpu_load.c \
	r600_perfcounter.c \
	r600_pipe_common.c \
	r600_pipe_common.h \
	r600_query.c \
	r600_query.h \
	r600_test_dma.c \
	r600_texture.c \
	radeon_uvd.c \
	radeon_uvd.h \
	radeon_vcn_dec.c \
	radeon_vcn_dec.h \
	radeon_vce_40_2_2.c \
	radeon_vce_50.c \
	radeon_vce_52.c \
	radeon_vce.c \
	radeon_vce.h \
	radeon_video.c \
	radeon_video.h \
	radeon_winsys.h
