# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_md2
crypto_md2_TEMPLATE = SUBLIBCRYPTO
crypto_md2_DEFS = OPENSSL_NO_DEPRECATED
crypto_md2_SOURCES = \
	md2_dgst.c \
	md2_one.c
$(evalcall VBOX_OPENSSL_X86,crypto_md2)

include $(FILE_KBUILD_SUB_FOOTER)
