/* $Id$ */
/** @file
 * BS3Kit - Undefining function mangling - automatically generated by the bs3kit-mangling-code-undef.h makefile rule.
 */

/*
 * Copyright (C) 2007-2016 Oracle Corporation
 *
 * This file is part of VirtualBox Open Source Edition (OSE), as
 * available from http://www.virtualbox.org. This file is free software;
 * you can redistribute it and/or modify it under the terms of the GNU
 * General Public License (GPL) as published by the Free Software
 * Foundation, in version 2 as it comes in the "COPYING" file of the
 * VirtualBox OSE distribution. VirtualBox OSE is distributed in the
 * hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
 *
 * The contents of this file may alternatively be used under the terms
 * of the Common Development and Distribution License Version 1.0
 * (CDDL) only, as it comes in the "COPYING.CDDL" file of the
 * VirtualBox OSE distribution, in which case the provisions of the
 * CDDL are applicable instead of those of the GPL.
 *
 * You may elect to license modified versions of this file under the
 * terms and conditions of either the GPL or the CDDL or both.
 */


#undef Bs3A20Disable
#undef Bs3A20DisableViaKbd
#undef Bs3A20DisableViaPortA
#undef Bs3A20Enable
#undef Bs3A20EnableViaKbd
#undef Bs3A20EnableViaPortA
#undef Bs3KbdRead
#undef Bs3KbdWait
#undef Bs3KbdWrite
#undef Bs3MemAlloc
#undef Bs3MemAllocZ
#undef Bs3MemCpy
#undef Bs3MemFree
#undef Bs3MemMove
#undef Bs3MemPCpy
#undef Bs3MemZero
#undef Bs3PagingInitRootForLM
#undef Bs3PagingInitRootForPAE
#undef Bs3PagingInitRootForPP
#undef Bs3PagingProtect
#undef Bs3PagingProtectPtr
#undef Bs3Panic
#undef Bs3PicMaskAll
#undef Bs3PrintChr
#undef Bs3Printf
#undef Bs3PrintfV
#undef Bs3PrintStr
#undef Bs3PrintStrN
#undef Bs3PrintU32
#undef Bs3PrintX32
#undef Bs3RegCtxConvertToRingX
#undef Bs3RegCtxPrint
#undef Bs3RegCtxRestore
#undef Bs3RegCtxSave
#undef Bs3SelFlatCodeToRealMode
#undef Bs3SelFlatCodeToProtFar16
#undef Bs3SelFar32ToFlat32
#undef Bs3SelProtFar32ToFlat32
#undef Bs3SelProtModeCodeToRealMode
#undef Bs3SelRealModeCodeToProtMode
#undef Bs3Shutdown
#undef Bs3SlabAlloc
#undef Bs3SlabAllocEx
#undef Bs3SlabFree
#undef Bs3SlabInit
#undef Bs3SlabListAdd
#undef Bs3SlabListAlloc
#undef Bs3SlabListAllocEx
#undef Bs3SlabListFree
#undef Bs3SlabListInit
#undef Bs3StrCpy
#undef Bs3StrFormatV
#undef Bs3StrLen
#undef Bs3StrNLen
#undef Bs3StrPrintf
#undef Bs3StrPrintfV
#undef Bs3TestCheckRegCtxEx
#undef Bs3TestFailed
#undef Bs3TestFailedF
#undef Bs3TestFailedV
#undef Bs3TestInit
#undef Bs3TestPrintf
#undef Bs3TestPrintfV
#undef Bs3TestSkipped
#undef Bs3TestSkippedF
#undef Bs3TestSkippedV
#undef Bs3TestSub
#undef Bs3TestSubDone
#undef Bs3TestSubErrorCount
#undef Bs3TestSubF
#undef Bs3TestSubV
#undef Bs3TestTerm
#undef Bs3Trap16Init
#undef Bs3Trap16InitEx
#undef Bs3Trap16SetGate
#undef Bs3Trap32Init
#undef Bs3Trap32SetGate
#undef Bs3Trap64Init
#undef Bs3Trap64SetGate
#undef Bs3TrapDefaultHandler
#undef Bs3TrapPrintFrame
#undef Bs3TrapRmV86SetGate
#undef Bs3TrapSetHandler
#undef Bs3TrapSetJmp
#undef Bs3TrapSetJmpAndRestore
#undef Bs3TrapUnsetJmp

