#
# Copyright (C) 2010 Oracle Corporation
#
# This file is part of VirtualBox Open Source Edition (OSE), as
# available from http://www.virtualbox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualBox OSE distribution. VirtualBox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#
ifeq ($(KBUILD_HOST),darwin)
 VBOX_BIN=/Applications/VirtualBox.app/Contents/MacOS
 VBOX_SDK=$(VBOX_BIN)/sdk
# JAVA_ARGS += -d32
endif

ifeq ($(KBUILD_HOST),linux)
 VBOX_BIN=/home/nike/work/ws/out/linux.amd64/debug/bin
 VBOX_SDK=$(VBOX_BIN)/sdk
endif

ifeq ($(KBUILD_HOST),win)
 VBOX_BIN=e:/ws/out/win.amd64/debug/bin
 VBOX_SDK=$(VBOX_BIN)/sdk
 JACOB_DIR=s:/jacob-1.15-M3/
 JACOB_JAR=$(JACOB_DIR)/jacob.jar
 CLASSPATH += $(JACOB_JAR)$(SEP)
 JAVA_ARGS += -Djava.library.path=$(JACOB_DIR)
endif

ifeq ($(KBUILD_HOST),win)
 VBOX_JAR=$(VBOX_SDK)/bindings/mscom/java/vboxjmscom.jar
 SEP=\;
else
 VBOX_JAR=$(VBOX_SDK)/bindings/xpcom/java/vboxjxpcom.jar
 SEP=:
endif

VBOX_JAR_WS=$(VBOX_SDK)/bindings/webservice/java/jax-ws/vboxjws.jar

JAVA_ARGS += -Dvbox.home=$(VBOX_BIN)
CLASSPATH  := $(CLASSPATH)$(VBOX_JAR)$(SEP).

all: testvb

testvb:
	javac -cp $(VBOX_JAR) TestVBox.java
	java $(JAVA_ARGS) -cp $(CLASSPATH)  TestVBox


testws:
	javac -cp $(VBOX_JAR_WS) TestVBox.java
	java $(JAVA_ARGS) -cp $(VBOX_JAR_WS)$(SEP)$(CLASSPATH) TestVBox -w -url http://localhost:18083
