# $Id: Makefile.kmk 118412 2017-10-17 14:26:02Z bird $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2006-2017 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_rc4
crypto_rc4_TEMPLATE = SUBLIBCRYPTO
crypto_rc4_DEFS = OPENSSL_NO_DEPRECATED
crypto_rc4_SOURCES = \
	rc4_enc.c \
	rc4_skey.c
$(evalcall VBOX_OPENSSL_X86,crypto_rc4)

include $(FILE_KBUILD_SUB_FOOTER)
