# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

if 0 # Disabled following OL's example.
LIBRARIES += crypto_sm4
crypto_sm4_TEMPLATE = SUBLIBCRYPTO
crypto_sm4_DEFS = OPENSSL_NO_DEPRECATED
crypto_sm4_SOURCES = \
	sm4.c
$(evalcall VBOX_OPENSSL_X86,crypto_sm4)
endif

include $(FILE_KBUILD_SUB_FOOTER)
