# $Id: Makefile.kmk 118412 2017-10-17 14:26:02Z bird $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2016-2017 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_ripemd
crypto_ripemd_TEMPLATE = SUBLIBCRYPTO
crypto_ripemd_DEFS = OPENSSL_NO_DEPRECATED
crypto_ripemd_SOURCES = \
	rmd_dgst.c

$(evalcall VBOX_OPENSSL_X86,crypto_ripemd)

include $(FILE_KBUILD_SUB_FOOTER)
