# $Id$
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_buffer
crypto_buffer_TEMPLATE = SUBLIBCRYPTO
crypto_buffer_DEFS = OPENSSL_NO_DEPRECATED
crypto_buffer_SOURCES = \
	buf_err.c \
	buffer.c
$(evalcall VBOX_OPENSSL_X86,crypto_buffer)

include $(FILE_KBUILD_SUB_FOOTER)
